version: '3.7'

networks: 
  spark:

services: 

  spark:
    image: my-spark:3.1.2
    container_name: spark
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '7077:7077'
      - '4040:4040'
    volumes: 
      - ./apps:/opt/apps
