version: '3.7'

services:
  spark:
    image: datamec:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-app
    volumes:
      - ./example.py:/opt/application/example.py
    command: driver local:///opt/application/example.py
