version: '3.7'

services:
    elasticsearch:
        image: elasticsearch:7.12.1
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
        volumes:
            - ./elastic_data:/user/share/elasticsearch/data
        user: "1000:0"
        ports: 
            - 9200:9200
    kibana:
        image: kibana:7.12.1
        container_name: kibana
        user: "1000:0"
        ports: 
            - 5601:5601
